---
apiVersion: networkservicemesh.io/v1
kind: NetworkService
metadata:
  name: vl3-scale-from-zero
spec:
  payload: IP
  matches:
    - source_selector:
      fallthrough: true
      routes:
        - destination_selector:
            app: nse-vl3-vpp
            nodeName: "{{.nodeName}}"
    - source_selector:
        capability: vl3
      fallthrough: true
      routes:
        - destination_selector:
            capability: vl3
    - source_selector:
      routes:
        - destination_selector:
            app: icmp-responder-supplier
